/usr/bin/python3.6: can't open file '/home/ubuntu/test-bigdata/adminmgr/media/code/A2/python/task/BD_1621_1634_1906_SHJ0lmJ.py': [Errno 2] No such file or directory
