/usr/bin/python3.6: can't open file '/home/ubuntu/test-bigdata/adminmgr/media/code/A2/python/task/BD_0012_0792_0948_1324.py': [Errno 2] No such file or directory
